module.exports.Questions = "Trivia by Americhino"
   module.exports.QText   = Math.floor(Math.random() * 20); // The questions
   module.exports.QAnswer = module.exports.QText; // The correct answers
   // OK, set the questions
   module.exports.QText[0] = "What is the capital of Norway?";
   module.exports.QText[1] = "What is the capital of Hungary?";
   module.exports.QText[2] = "What is the capital of Cyprus?";
   module.exports.QText[3] = "What is the capital of Libya?";
   module.exports.QText[4] = "What is the capital of Kenya?";
   module.exports.QText[5] = "What is the capital of Nigeria?";
   module.exports.QText[6] = "What is the capital of Columbia?";
   module.exports.QText[7] = "What is the capital of Barbados?";
   module.exports.QText[8] = "What is the capital of Australia?";
   module.exports.QText[9] = "What is the capital of Pakistan?";
   module.exports.QText[10] = "What is the capital of Spain?";
   module.exports.QText[11] = "What is the capital of England?";
   module.exports.QText[12] = "What is the capital of Ireland?";
   module.exports.QText[13] = "What is the capital of Sweden?";
   module.exports.QText[14] = "What is the capital of Denmark?";
   module.exports.QText[15] = "What is the capital of Poland?";
   module.exports.QText[16] = "What is the capital of Italy?";
   module.exports.QText[17] = "What is the capital of India?";
   module.exports.QText[18] = "What is the capital of Canada?";
   module.exports.QText[19] = "What is the capital of Portugal?";
   // Set the correct answers
   module.exports.QAnswer[0] = "Oslo";
   module.exports.QAnswer[1] = "Budapest";
   module.exports.QAnswer[2] = "Nicosia";
   module.exports.QAnswer[3] = "Tripoli";
   module.exports.QAnswer[4] = "Nairobi";
   module.exports.QAnswer[5] = "Lagos";
   module.exports.QAnswer[6] = "Bogota";
   module.exports.QAnswer[7] = "Bridgetown";
   module.exports.QAnswer[8] = "Canberra";
   module.exports.QAnswer[9] = "Islamabad";
   module.exports.QAnswer[10] = "Madrid"; // No cheating!
   module.exports.QAnswer[11] = "London";
   module.exports.QAnswer[12] = "Dublin";
   module.exports.QAnswer[13] = "Stockholm";
   module.exports.QAnswer[14] = "Copenhagen";
   module.exports.QAnswer[15] = "Warsaw";
   module.exports.QAnswer[16] = "Rome";
   module.exports.QAnswer[17] = "New Delhi";
   module.exports.QAnswer[18] = "Ottawa";
   module.exports.QAnswer[19] = "Portugal";
