module.exports.Questions = "Trivia by Americhino"
   module.exports.QText   = new Array(1); // The questions
   module.exports.QAnswer = new Array(1); // The correct answers
   module.exports.QChoice = new Array(80); // The possible multi-choice values
   module.exports.QSelect = this.QSelect

   // Umm try to make QSelect a thing
   this.QSelect = Math.floor(Math.random() * module.exports.QText.length);
   // OK, set the questions
   this.QText[0] = "What is the capital of Norway";
   this.QText[1] = "What is the capital of Hungary";
   this.QText[2] = "What is the capital of Cyprus";
   this.QText[3] = "What is the capital of Libya";
   this.QText[4] = "What is the capital of Kenya";
   this.QText[5] = "What is the capital of Nigeria";
   this.QText[6] = "What is the capital of Columbia";
   this.QText[7] = "What is the capital of Barbados";
   this.QText[8] = "What is the capital of Australia";
   this.QText[9] = "What is the capital of Pakistan";
   this.QText[10] = "What is the capital of Spain";
   this.QText[11] = "What is the capital of England";
   this.QText[12] = "What is the capital of Ireland";
   this.QText[13] = "What is the capital of Sweden";
   this.QText[14] = "What is the capital of Denmark";
   this.QText[15] = "What is the capital of Poland";
   this.QText[16] = "What is the capital of Italy";
   this.QText[17] = "What is the capital of India";
   this.QText[18] = "What is the capital of Canada";
   this.QText[19] = "What is the capital of Portugal";

   // Now, set the possible choices
   this.QChoice[0] = "Bergen";
   this.QChoice[1] = "Trondheim";
   this.QChoice[2] = "Oslo";
   this.QChoice[3] = "Haugesund";
   this.QChoice[4] = "Warsaw";
   this.QChoice[5] = "Budapest";
   this.QChoice[6] = "Bucharest";
   this.QChoice[7] = "Vienna";
   this.QChoice[8] = "Crete";
   this.QChoice[9] = "Nicosia";
   this.QChoice[10] = "Athens";
   this.QChoice[11] = "Saloniki";
   this.QChoice[12] = "Tehran";
   this.QChoice[13] = "Cairo";
   this.QChoice[14] = "Tripoli";
   this.QChoice[15] = "Baghdad";
   this.QChoice[16] = "Nairobi";
   this.QChoice[17] = "Mombasa";
   this.QChoice[18] = "Zanzibar";
   this.QChoice[19] = "Kampala";
   this.QChoice[20] = "Laos";
   this.QChoice[21] = "Harare";
   this.QChoice[22] = "Douala";
   this.QChoice[23] = "Lagos";
   this.QChoice[24] = "Bogota";
   this.QChoice[25] = "Cali";
   this.QChoice[26] = "Medellin";
   this.QChoice[27] = "Panama";
   this.QChoice[28] = "Havana";
   this.QChoice[29] = "Bridgetown";
   this.QChoice[30] = "Kingston";
   this.QChoice[31] = "Montego Bay";
   this.QChoice[32] = "Sydney";
   this.QChoice[33] = "Brisbane";
   this.QChoice[34] = "Melbourne";
   this.QChoice[35] = "Canberra";
   this.QChoice[36] = "Kabul";
   this.QChoice[37] = "Karachi";
   this.QChoice[38] = "Islamabad";
   this.QChoice[39] = "New Delhi";
   this.QChoice[40] = "Bergen";
   this.QChoice[41] = "Madrid";
   this.QChoice[42] = "Oslo";
   this.QChoice[43] = "Haugesund";
   this.QChoice[44] = "London";
   this.QChoice[45] = "Budapest";
   this.QChoice[46] = "Bucharest";
   this.QChoice[47] = "Vienna";
   this.QChoice[48] = "Crete";
   this.QChoice[49] = "Dublin";
   this.QChoice[50] = "Athens";
   this.QChoice[51] = "Saloniki";
   this.QChoice[52] = "Tehran";
   this.QChoice[53] = "Stockholm";
   this.QChoice[54] = "Tripoli";
   this.QChoice[55] = "Baghdad";
   this.QChoice[56] = "Nairobi";
   this.QChoice[57] = "Mombasa";
   this.QChoice[58] = "Copenhagen";
   this.QChoice[59] = "Kampala";
   this.QChoice[60] = "Warsaw";
   this.QChoice[61] = "Harare";
   this.QChoice[62] = "Douala";
   this.QChoice[63] = "Lagos";
   this.QChoice[64] = "Bogota";
   this.QChoice[65] = "Cali";
   this.QChoice[66] = "Medellin";
   this.QChoice[67] = "Rome";
   this.QChoice[68] = "New Delhi";
   this.QChoice[69] = "Bridgetown";
   this.QChoice[70] = "Kingston";
   this.QChoice[71] = "Montego Bay";
   this.QChoice[72] = "Sydney";
   this.QChoice[73] = "Brisbane";
   this.QChoice[74] = "Ottawa";
   this.QChoice[75] = "Canberra";
   this.QChoice[76] = "Kabul";
   this.QChoice[77] = "Karachi";
   this.QChoice[78] = "Islamabad";
   this.QChoice[79] = "Lisbon";

   // Set the correct answers
   this.QAnswer[0] = 2;
   this.QAnswer[1] = 5;
   this.QAnswer[2] = 9;
   this.QAnswer[3] = 14;
   this.QAnswer[4] = 16;
   this.QAnswer[5] = 23;
   this.QAnswer[6] = 64;
   this.QAnswer[7] = 69;
   this.QAnswer[8] = 72;
   this.QAnswer[9] = 38;
   this.QAnswer[10] = 41; // No cheating!
   this.QAnswer[11] = 44;
   this.QAnswer[12] = 49;
   this.QAnswer[13] = 53;
   this.QAnswer[14] = 58;
   this.QAnswer[15] = 4;
   this.QAnswer[16] = 67;
   this.QAnswer[17] = 39;
   this.QAnswer[18] = 74;
   this.QAnswer[19] = 79;
